services:
  api:
    build:
      dockerfile: ./Calendario.API/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - db
    networks:
      - net-mock-service-network

  db:
    image: postgres:${POSTGRES_VERSION}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-d",
          "${POSTGRES_DB}",
          "-U",
          "${POSTGRES_USER}"
        ]
      timeout: 5s
      retries: 5
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    networks:
      - net-mock-service-network

networks:
  net-mock-service-network:


volumes:
  database_data:
